### ISSUE TITLE
Add pls: Proton Mail and Minds.com

### ISSUE THREAD

**Issue by bobea** [nylira/prism-break#1424] opened 2015-10-10 23:03 UTC
Already using them and i think they should be on list :)
Proton Mail - email service 
https://protonmail.ch/

Minds.com - social network
https://www.minds.com/

**Comment by mastercoms** [comment] 2015-10-11 00:02
ProtonMail has been [discussed](https://github.com/nylira/prism-break/issues/461) [elsewhere](https://github.com/nylira/prism-break/issues/1412), and it is not fully open source.

Minds requires Google Play.

**Comment by bobea** [comment] 2015-10-11 22:39
Minds is opensource and you dont need to download app to use it, you can use web browser :)

**Comment by alerque** [comment] 2015-10-12 07:05
Please don't suggest multiple systems in an issue, it makes discussion hard to track. In any event the proton mail part of this is a duplicate of #1412.

Minds on the other hand doesn't look  like something I'm interested in seeing recommended until it's gotten much more of a shake out in the open source world. First of all it's labeled as alpha (or some components as beta) and we generally don't recommend pre-release software unless there is a compelling reason to do so. I see none in this case. On that ground I suggest closing this issue for now. If at a later date the system matures either this issue can be re-opened or a new issue dedicated it discussing it.

Such a discussion should include a clear presentation of what the software does, what proprietary systems it replaces, how its architecture keeps its users safe from dragnet surveillance, any technical reviews or code auditing that has happened to date, and how it stacks up against other entries in the category as far as security and privacy goes. Just saying "hey add this open source thing" is not enough to merit inclusion.

Besides the _current_ disqualifying issue above, I have to say I'm skeptical of the direction the project is headed and it's ability to reach that goal in a way that is actually going to fit the goals of this project. Besides not actually being an end user product so much as a toolkit to build end user products (how does this help PRISM-Break users?), the overall scope is pretty nebulous at this point. From the FAQ:

> Minds seeks to open source and free all code in the world, ensuring that future humans are fully aware of any computer programs influencing their daily lives.  We also seek to create the software for a fully decentralized and democratized union of technology and the human being.

**Comment by Zegnat** [comment] 2015-10-12 12:49
I am going to close this, mostly because I am unable to find the source code behind Minds, which makes every other argument useless.

The closest thing they have to source code is a 2 year old [fork of idno](https://github.com/Minds/idno), now known as [Known](http://withknown.com/) which is a self-hostable social platform based on [IndieWeb](https://indiewebcamp.com) protocols. We might as well recommend Known then, which might be a good idea either way.

**Closed by Zegnat** 2015-10-12 12:49 UTC

**Comment by alerque** [comment] 2016-11-12 07:53
I'm not sure it's ready to be suggested for inclusion yet, but there does seem to be some progress on the Minds project since I Iooked at it last. It's a lot clearer what's what component wise and [the source code has made an appearance on Github](https://github.com/Minds). If somebody wants to review it in light of the discussion points above there might be something worth proposing.
