### ISSUE TITLE
Add turtl

### ISSUE THREAD

**Issue by gygygh** [nylira/prism-break#1701] opened 2017-03-06 17:45 UTC
https://turtlapp.com/

**Comment by Hillside502** [comment] 2017-03-06 17:51
@gygygh 
Hmm --- looks like another processed pork account created 8 minutes ago

**Comment by gygygh** [comment] 2017-03-06 18:31
Yes, because I opened it to ask questions. I want to know if Turtl is safe. I said "Add" because it seemed safe to me. If not, I will learn. There has not been a conclusion about this application before. I'm following the Prism-break platform and I'm asking questions. That's why I opened my account. How is that strange?

**Comment by strugee** [comment] 2017-03-07 14:32
Duplicate of #1602

**Closed by strugee** 2017-03-07 14:32 UTC
