### ISSUE TITLE
Maybe Consider CloudFlare DNS 

### ISSUE THREAD

**Issue by loo11** [nylira/prism-break#1970] opened 2018-05-16 08:52 UTC
Hey maybe you should add Cloudflare to the DNS recommendations 
Here : everything to know about 
https://blog.cloudflare.com/announcing-1111/
what do you think

**Comment by yegortimoshenko** [comment] 2018-05-16 08:55
Duplicate of #1938.

**Closed by yegortimoshenko** 2018-05-16 08:55 UTC
