### ISSUE TITLE
Could you recommend a secure antivirus program

### ISSUE THREAD

**Issue by laprasx** [nylira/prism-break#1622] opened 2016-11-30 22:06 UTC
Which antivirus programs are safe?

**Comment by strugee** [comment] 2016-11-30 22:17
This question incorrectly assumes that an antivirus program is necessary in the first place.

Generally speaking PRISM Break's recommendation is to install a secure and trustworthy operating system and only install software from trusted sources (i.e. your chosen operating system's repositories). Such a setup will do a much better job of protecting you than antivirus software, since the mere concept of antivirus software is generally fundamentally flawed. The "enumerating badness" section of http://www.ranum.com/security/computer_security/editorials/dumb/ does a good job talking about this.

**Comment by Zegnat** [comment] 2016-12-01 11:07
Closing this as a duplicate of #727. The first comment there will actually point you at an open-source AV alternative.

**Closed by Zegnat** 2016-12-01 11:07 UTC
