### ISSUE TITLE
Firefox Add-On: "ublock origin" instead of "ublock"

### ISSUE THREAD

**Issue by bugreport0** [nylira/prism-break#1312] opened 2015-05-31 17:08 UTC
More features, support...

**Comment by Zegnat** [comment] 2015-05-31 19:47
Duplicate of #1291, new arguments are welcome there. My sum-up:

> <i>[…]</i> if we recommend the main repository it would get both new features by Chris and bug fixes by Raymond. If we recommend the uBlock Origin fork it will only be Raymond’s bug fixes, as he isn’t planning to add new features (for now).

**Closed by Zegnat** 2015-05-31 19:47 UTC

**Comment by vyp** [comment] 2015-07-15 16:24
@Zegnat And gorhill already responded to that...?
