### ISSUE TITLE
Add an "hosts files" section

### ISSUE THREAD

**Issue by geplus** [nylira/prism-break#1404] opened 2015-09-21 11:50 UTC
Hi,
I'm asking to add an "hosts files" section, with a list of best pre-compiled hosts files.

I' ve only found only the great Dan Pollock's http://someonewhocares.org , at the moment.

**Comment by Zegnat** [comment] 2015-09-21 11:58
Closing this as a duplicate of #1308. For more discussion #1117 is about an Android app that uses hosts files.

**Closed by Zegnat** 2015-09-21 11:58 UTC
