### ISSUE TITLE
Thoughts & Actions on Microsoft's Github aquisition

### ISSUE THREAD

**Issue by 2SI3NX** [nylira/prism-break#2015] opened 2018-06-04 18:30 UTC
Not sure if you consider this a petty issue, but to many other people and me it seems like this is the ultimate shit storm that will hit all open source code in the very near future.  Do we really want that to happen?
Since prism-break is a small and precise hub of most privacy related open-source software, i advise we get the attention of at least those software developers to move away from Github and onto an open source alternative that will not be controlled by a giant that already controls half the internet.  

If we stand together, we can continue our journey of freedom and open source/self-hosted software elsewhere such as Gitlab.
here is something i stumbled upon on what microsoft is capable of doing just like its done in the past.
https://jacquesmattheij.com/what-is-wrong-with-microsoft-buying-github

I respect prism-break for putting together a nice safe list, but it would be for nothing if you do not at least make this apparent to those developers and caution them.

**Comment by strugee** [comment] 2018-06-04 21:29
Closing as a duplicate of #2011.

**Closed by strugee** 2018-06-04 21:29 UTC
