### ISSUE TITLE
404 Not Found on PRISM Break homepage

### ISSUE THREAD

**Issue by wzh190015** [nylira/prism-break#1863] opened 2018-01-18 11:34 UTC
https://prism-break.org

**Comment by strugee** [comment] 2018-01-18 16:45
Looks like this was caused by the merges I did yesterday. I'm running a rebase.

**Comment by strugee** [comment] 2018-01-18 16:51
I can't reproduce locally (with a fresh clone and a fresh `npm install`) with `make en`. I'm trying now with plain `make`.

**Comment by alerque** [comment] 2018-01-18 17:16
@strugee I don't think this is a build problem, something else happened to the live deployment.

**Comment by strugee** [comment] 2018-01-18 17:27
@alerque yeah, `make` just finished fine for me. I'm emailing @nylira.

(The reason I thought it was a build problem instead of a deployment problem was https://github.com/nylira/prism-break-static/commit/a209089097f767cf04e6b5a075b00fe144c5f80b).

**Comment by alerque** [comment] 2018-01-18 17:49
@strugee Definitely something in the [sync target](https://github.com/nylira/prism-break/blob/0da00844d4530d35c2069e944a309079d475438e/Makefile#L150) didn't run right, probably sync got run after a `make clean` but having not done a `make all` at all (or not having checked that it ran!). We discussed adding `full` as a prerequisite for `sync` at some point, this would be the kind of mistake that would nip in the bud. There was some reason we didn't add it but I can't remember what that was.

**Comment by strugee** [comment] 2018-01-18 18:04
@alerque I poked around the issue tracker and didn't find anything. I don't really see why we _shouldn't_ add `full` as a dependency of `sync`. But you're the expert on the Makefile.

**Comment by nylira** [comment] 2018-01-18 18:09
I think I know the problem. I had to reinstall node locally and the version of livescript I installed for Prism Break was too new, causing nothing to be generated. The updated site will be up soon -- building the files right now. Thanks for the ping, and apologies for the downtime.

**Comment by alerque** [comment] 2018-01-18 18:16
@nylira  Isn't that something the [`package.json`](https://github.com/nylira/prism-break/blob/0da00844d4530d35c2069e944a309079d475438e/package.json#L10) should have caught and taken care of?

With however you had a broken build environment, did the `make all` not produce an error? Or did you just not notice and `make sync` anyway? What you you think of making a full successful build a prerequisite of the sync target? Would that have caught this case?

**Comment by nylira** [comment] 2018-01-18 18:18
What would catch this is using the package.json `lsc`, not a system-installed `lsc` in the Makefile.

**Comment by alerque** [comment] 2018-01-18 18:20
Oh good call. That can be fixed with some PATH manipulations in the Makefile so the local one gets used in preference to a system on. I'll submit something for that.

**Comment by nylira** [comment] 2018-01-18 18:22
@alerque thank you!

**Comment by strugee** [comment] 2018-01-22 06:18
@alerque do you want to keep this open as a tracker for the Makefile fixes? Or should I close?

**Comment by alerque** [comment] 2018-01-22 11:58
Lets keep it, I was keeping this tab open just in case but I think it makes sense to keep the issue open until I fix this as a direct link between the code problem we'll fix and the 404 that resulted.

**Closed** 2018-02-22 17:05 UTC
Labels: ops
