### ISSUE TITLE
Linux Mint Debian Edition removed?

### ISSUE THREAD

**Issue by radiorapido** [nylira/prism-break#982] opened 2014-05-14 11:09 UTC
Just noticed that LMDE seems not to be on the list of recommended operating systems.

I am just wondering why this might have been removed.

I currently use Linux Mint Maya MATE edition, but was thinking of moving to LMDE... now I'm confused.

thanks in advance

**Comment by yegortimoshenko** [comment] 2018-03-10 00:02
Closing as duplicate of #805 (see f66bfb6cdd3904ce51ba0bf28d3f0255838e8286).

**Closed by yegortimoshenko** 2018-03-10 00:02 UTC
