### ISSUE TITLE
Most android messenger suggestions suck

### ISSUE THREAD

**Issue by hasufell** [nylira/prism-break#1672] opened 2017-01-27 15:21 UTC
Most of the recommendations look like unreliable crap to me.

* Ring: I don't get any messages, although one was sent from the other side
* Kontalk: same as with Ring
* Riot: can't even register

ChatSecure works, but that has low usability and requires xmpp stuff. Probably not something you can convince someone to try.

Any non-SMS and non-XMPP "whatsapp-like" things out there that don't suck for low-tech users?

**Comment by alerque** [comment] 2017-01-27 15:37
Yes. Signal.

We've [talked this to death](https://github.com/nylira/prism-break/issues?utf8=%E2%9C%93&q=is%3Aissue%20signal%20) and aren't listing it for reasons of dependencies, but it's much the most reliable and easiest to use option out there. It's what I recommend in person and use myself because I trust that with it the everyday users on the end of the line I need to communicate with are better secured than anything else I could realistically use with them.

I've been stewing over this for a while too because conceptually there are better solutions for things but what's listed on PRISM-Break is often not the most usable options. In the real world most people make compromises and Signal is the best balance of compromises most people can make right now. Yet we can't  list it.

Or can we?

I've been contemplating a graded recommendation system that scores a couple different aspects of each program and shows grades in each category for each listing then leaves people to sort through what trade offs they want to make themselves. This would bridge the gab between ideal solution concepts that don't work very well yet and proprietary systems that work but are horrible concepts.

For example Signal might be A+ for cryptographic security, B for openness (client and protocol open source but relies on Google Play services), A for usability, A for audited, etc.

**Comment by hasufell** [comment] 2017-01-27 16:22
The rating is an interesting idea and might also solve controversies like in #1663 but _only_ given we can create a useful score system. I'm not sure. That also sounds like a lot of work and maybe technical guessing, which we should avoid.

Wrt signal... well, not even on F-Droid, so.

**Comment by alerque** [comment] 2017-01-27 16:33
WRT Signal, I was going to say above and forgot ... it's not on F-Droid's main repo because of key signing issues but there are [F-Droid builds](https://guardianproject.info/fdroid/). It is a [deterministic compile](https://whispersystems.org/blog/reproducible-android/) (amazingly) so you can even validate builds distributed through Google Play.

**Comment by hasufell** [comment] 2017-01-27 17:21
I have the guardian repo activated but I still don't see it

**Comment by Hillside502** [comment] 2017-01-27 20:10
Looks like Signal isn't on The Guardian Project's F-Droid repository --- just Google Play and iTunes:-

https://guardianproject.info/apps/
https://www.whispersystems.org/

The venerable Mr Snowden's endorsement appears on the latter :1st_place_medal: 

Right on!

**Comment by strugee** [comment] 2017-01-27 20:44
Agreed that most of the messengers suck - I too teach, recommend and use Signal almost exclusively.

I'd support a grading system if we have the manpower to support it (and that's a big if). I've also been thinking for a while about some sort of slider, conceptually similar to Tor Browser's security slider - setting it to "low" would show a large warning but also recommendations for iPhones, etc.; the default of "medium" would show stuff like Signal that are pretty good but make some compromises for usability; the "high" setting would show only the strictest projects.

**Comment by anthologist** [comment] 2017-01-27 21:29
I think Conversations is very easy...

**Comment by strugee** [comment] 2017-01-27 23:40
@anthologist Conversations is probably the best on the list. However it still requires the user to have an XMPP account set up, which is intimidating for some people. Especially compared with e.g. Signal.

**Comment by bezcitu** [comment] 2017-01-28 13:41
@strugee 
Having an XMPP account is far more privacy-friendly then using your phone number in order to use a messenger. It is also possible to directly create an XMPP account in Conversations on servers which support this feature.

**Comment by strugee** [comment] 2017-01-28 17:12
@bezcitu I'm aware. That has no bearing on the UX impact. Especially when we discuss all suggestions currently on the site, not just Conversations (which is unusually good).

**Comment by hasufell** [comment] 2017-01-28 18:14
Conversations indeed seems to be a good option. But then you have to deal with all the xmpp problems: group chat is hard an needs to be supported server- side,  file transfer is often broken, depending on server encryption settings you might not see some clients etc etc

**Comment by strugee** [comment] 2017-01-28 21:47
@hasufell very true. FWIW all that stuff works extremely well with a well-configured server, but a lot of servers aren't well-configured. :/

The conversations.im server is unsurprisingly great about that, but it also costs (IIRC) £5/month.

**Comment by jinformatique** [comment] 2017-02-01 11:09
Why continue to recommand Signal, when there is now a really good alternative to Signal which doesn't need mobile number to signup?
It's called **Wire**: https://wire.com/
I'm using it since 4 months ago and adopted it. All the conversation are e2e encrypted. It's very useful to use Wire on AOSP ROMs without gapps, because Signal cannot be installed on such ROMs.

@hasufell I come from a place where I used/tryed Ring, Kontalk, Riot, ChatSecure as well and it sucked.
> Any non-SMS and non-XMPP "whatsapp-like" things out there that don't suck for low-tech users?

I really agree with you on this point. That's why I found Wire really working even for video call without crashing. It was easy for low-tech family and friends to adopt it.

**Comment by strugee** [comment] 2017-02-01 15:29
@jinformatique Wire isn't on the list yet, so let's keep discussion about it in its respective issue, please.

**Comment by jinformatique** [comment] 2017-02-02 14:03
@strugee Signal is not on the list as well and people are able to recommend it here.

**Comment by alerque** [comment] 2017-02-02 14:26
@jinformatique This here (Github issues) is not where PRISM-Break recommendations are made. This is where we _discuss_ what to recommend. Anybody who has something in mind can bring it up, they can be discussed, then and contributors and experts can weight the pros and cons and decide what to put on the actual site. A bunch of individuals noting that we personally recommend something to our friends as a data point in this discussion does not make it a PRISM-Break recommendation (even if the person saying it happens to be a contributor or resident expert).

**Comment by jinformatique** [comment] 2017-02-02 15:13
@alerque I completely agree and I'm sorry if I got misunderstood. I wanted to personally recommend Wire here as I know it is not on PRISM-Break list.

@hasufell opened this topic and you and some others replied mentioning only Signal as if it's the only option. So I just wanted to do the same and tell @hasufell that there is something else. In the discussion there should be place to mention Signal and Wire, not just Signal. Both are not perfect for different reasons and people here should be aware of that.

**IM comparison table**
http://xn--4ca9a.eu/bac.html

**Comment by hasufell** [comment] 2017-02-02 15:53
This issue is about the entirety of the "android messenger" section and if and how to rework it. It's fine to mention apps that are not on the list, but more detailed discussions could probably be taken to the respective issues, if any.

**Comment by strugee** [comment] 2017-02-04 10:54
:thumbsup: I'd like to echo what @alerque said. Me mentioning that I recommend Signal doesn't imply that it will be/should be recommended on PRISM Break, even though I have "Collaborator" next to my name.

Now, I'd like to find a way to list Signal that's compatible with PRISM Break's goals. But we're not going to change the criteria, etc. to do so.

**Comment by hasufell** [comment] 2017-02-06 09:20
WRT Conversations: I noticed that images/file attachments may get uploaded to a conversations.im server and stored there __publicly accessible__, at least if you know the url. I noticed that while I got a message from a conversations.im user while I was logged into my own jabber account via pidgin. Instead of an image, I got a url pointing to a user-specific url on the conversations server of the form `https://share.conversations.im/<username>/<hash-or-something>.jpg`. It's reproducible.

IMO, this breaks privacy. And  it's neither intuitive, nor obvious to the user.

**Comment by anthologist** [comment] 2017-02-08 21:42
@hasufell We (and Prism Break) are speaking about the Conversations client, not the xmpp server. It's up to you choosing your favourite domain account.

**Comment by strugee** [comment] 2017-02-08 23:56
@anthologist if you read the linked issue you'll note that the discussion was indeed about the Conversations client, not just the service.

However even if that weren't the case, if there's a problem specific to the conversations.im XMPP service, that's something we should take into account. Client defaults are important.

**Comment by yegortimoshenko** [comment] 2018-03-17 00:37
I want to close this issue because it's not actionable. Anyone against it?

**Closed** 2018-03-27 19:08 UTC
Labels: waiting for objections
