### ISSUE TITLE
Windows section is missing PDF readers , Microsoft office replacement 

### ISSUE THREAD

**Issue by theJaxon** [nylira/prism-break#1384] opened 2015-08-19 03:02 UTC
I just want to know why free and open source PDF readers such as SumatraPDF , Evince are not listed as a replacement for adobe reader and foxit reader ? 
Also why there's no replacement for microsoft office i mean isn't LibreOffice supposed to be the replacement for it ?

**Comment by vyp** [comment] 2015-08-19 03:06
https://github.com/nylira/prism-break/issues/1155

**Comment by yegortimoshenko** [comment] 2018-03-11 14:45
Duplicate of #1155.

**Closed by yegortimoshenko** 2018-03-11 14:45 UTC
