### ISSUE TITLE
Add crypto-messenger Wire

### ISSUE THREAD

**Issue by DestinFaroda** [nylira/prism-break#1750] opened 2017-07-11 17:52 UTC
It would be great if you could add Wire to your list of recommended software.
https://wire.com/

Wire is a video-, audio- and text-chat software with e2ee that runs on all platforms (Linux, Android, iOz, Windoze and Mac. Unfortunately, nobody loves Sailfish OS...).
The client is open source (server components will follow soon and self-hosting is encouraged) and the code was audited by two companies that couldn't find fatal problems.
Wire has its HQ in Switzerland and it's funded by Skype co-founder Janus Friis. In the future, Wire would like to generate income by selling premium services (especially to businesses).

**Comment by strugee** [comment] 2017-07-11 18:00
Duplicate of #1582

**Closed by strugee** 2017-07-11 18:00 UTC
