### ISSUE TITLE
"Wire" messenger app

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#1565] opened 2016-09-09 22:21 UTC
Hello, what is with the "Wire" messenger app for android, here is the homepage (https://wire.com/), here are adresses from wikipedia (https://en.wikipedia.org/wiki/Comparison_of_instant_messaging_clients , https://de.wikipedia.org/wiki/Liste_von_mobilen_Instant-Messengern). In wikipedia looks "Wire" like Conversations, and that is listed in prism-break.org.

Thanks!

**Comment by yegortimoshenko** [comment] 2018-03-17 00:24
Duplicate of #1582 and #1750.

**Closed by yegortimoshenko** 2018-03-17 00:24 UTC
