### ISSUE TITLE
Nextcloud, fork from Owncloud

### ISSUE THREAD

**Issue by Guillaume99** [nylira/prism-break#1634] opened 2016-12-13 19:49 UTC
Nextcloud is a fork of Owncloud. 
As of today, version 11 is out, and the project is very interesting.

Can be used for :
  - file synchronisation
  - calendar, tasks, notes, ... (sync with webdav from almost any devices)
  - it is possible to use Collabora (Libre office online, as a replacement of Ms Office)
  - clients exists on Android, Iphone, Windows, MacOS, Linux, ...

all open source (on github)

**Comment by strugee** [comment] 2016-12-13 20:57
Dupe of #1551. Please close and search for duplicates next time. Thanks!

**Closed** 2016-12-13 21:46 UTC
Labels: duplicate
