### ISSUE TITLE
Remove Riseup from the list already!

### ISSUE THREAD

**Issue by GitHubHatesTor** [nylira/prism-break#1652] opened 2016-12-31 04:43 UTC
https://user.riseup.net/ticket/111777

**Comment by strugee** [comment] 2016-12-31 06:44
That link gives me a login form.

**Comment by alerque** [comment] 2016-12-31 08:12
This isn't helpful @GitHubHatesTor. Please stop opening new issues about this unless there is something really new to put on the table. We have several open issues discussing this already and the conversation is disjointed enough without new issues being opened. Also the link isn't reachable. Please add the relevant content to #1554 or #1652 if appropriate or expand this issue if it's really something different that has come up before. I'm not opposed to removing it but throwing out a sensational issue headline with no content doesn't us get there.

**Comment by strugee** [comment] 2016-12-31 17:10
Closing as a duplicate of #1554. Please keep discussion in one place.

**Closed by strugee** 2016-12-31 17:10 UTC
