### ISSUE TITLE
Orweb is dead, replaced by Orfox

### ISSUE THREAD

**Issue by ChaiTRex** [nylira/prism-break#1978] opened 2018-05-31 14:30 UTC
Orweb is [a current Android browser recommendation on PRISM Break](https://prism-break.org/en/categories/android/#web-browsers).

Here's [Orweb's download link on the Google Play Store](https://play.google.com/store/apps/details?id=info.guardianproject.browser). As you can see, it's gone. [Its project page](https://guardianproject.info/apps/orweb/) also says Orweb is obsolete and replaced by Orfox.

Please replace Orweb suggestions with Orfox.

**Comment by yegortimoshenko** [comment] 2018-05-31 15:49
Duplicate of #1418. If you want to help, please send a PR :-)

**Closed by yegortimoshenko** 2018-05-31 15:49 UTC
