### ISSUE TITLE
[Instant Messaging] [Video and Voice] Signal 2.0 for iOS now supports text messaging.

### ISSUE THREAD

**Issue by annonman** [nylira/prism-break#1239] opened 2015-03-02 20:29 UTC
Updated just today, Signal supports text AS WELL AS voice.

https://itunes.apple.com/us/app/signal-private-messenger/id874139669?mt=8

https://whispersystems.org/blog/the-new-signal/

Github:
https://github.com/WhisperSystems/Signal-iOS

Signal is FOSS by Open Whisper Systems.  It offers cross-platform text communication between Android (TextSecure) and voice via RedPhone on Android.

**Comment by annonman** [comment] 2015-08-02 03:08
Is there any reason Signal is not included?

**Comment by strugee** [comment] 2015-08-11 23:26
See #552

**Comment by yegortimoshenko** [comment] 2018-03-10 02:10
Duplicate of #552, #896, #1314, #1667.

**Closed by yegortimoshenko** 2018-03-10 02:10 UTC
