### ISSUE TITLE
chromium-deblobbed?

### ISSUE THREAD

**Issue by bn0785ac** [nylira/prism-break#1851] opened 2017-12-30 22:30 UTC
could you review some software?

inox-hard
inox-beta
inox-dev

all from arch user repository (aur) 

its chromium, with all crapware removed 
>its recomended use scriptsafe for get even more protection

**Comment by strugee** [comment] 2017-12-31 02:29
Duplicate of #1673

**Closed** 2017-12-31 02:29 UTC
