### ISSUE TITLE
Decentralized image hosting website: http://ipfs.pics/

### ISSUE THREAD

**Issue by ceyhanmolla** [nylira/prism-break#1434] opened 2015-10-23 08:42 UTC
Decentralized image hosting website: http://ipfs.pics/ #1434

**Comment by vyp** [comment] 2015-10-23 09:00
Just to clarify, this doesn't have anything to do with keeping things private, which is the focus for prism break. This is more to do with having a 'guarantee' (i think) of your image staying available. So things like avoiding censorship etc. While this is really cool, not sure if it's appropriate for the site.. unless I'm mistaken somehow? @cloutier would you like to clarify?

**Comment by hasufell** [comment] 2015-10-23 11:17
> it is given a hash

for curiosity, which algorithm?

**Comment by berrythesoftwarecodeprogrammar** [comment] 2015-10-23 11:29
https://ipfs.io/
looks interesting, is usable currently but still in development

**Comment by cloutier** [comment] 2015-10-23 14:19
@vyp is right. It doesn't do much that help against PRISM. We actually make everything public (though anonymous). Our goal is to prevent [link rot](https://en.wikipedia.org/wiki/Link_rot) that is caused by censorship, closing of web services, etc. Those political ideals are related, but they are not the same.

Our code is open source, so if someone is interested in running it as a hidden service on Tor, it could help though.

**Comment by fedor1113** [comment] 2016-11-21 18:01
IPFS is a really cool protocol in itself, but I agree that this is a little beside the point.

**Comment by vyp** [comment] 2017-08-03 09:45
I'm going to close this for the above reasons.

**Closed by vyp** 2017-08-03 09:45 UTC
