### ISSUE TITLE
ProtonMail new features, and questions

### ISSUE THREAD

**Issue by jzakiya** [nylira/prism-break#1666] opened 2017-01-10 16:54 UTC
I know ProtonMail has been raised before.  If I remember correctly, the major issue (at least at the time) was the open sourcing of the serverside code. Is this correct?

I use ProtonMail, since for privacy purpose, its arguably better for that purpose than gmail, which I use too.  ProtonMail has come out with new version 3.6 which introduces two factor authentication.

https://protonmail.com/blog/encrypted_email_authentication/

And it seem their roadmap addresses some server issues.

https://protonmail.com/blog/secure-email-roadmap/

So what currently are the disqualifying issues that keep it from being listed here?

**Comment by bezcitu** [comment] 2017-01-14 17:25
There are several issues, see #1611, #1604, #1412, #1383 and #1204. Reading this should also clarify the reason why ProtonMail is still and will always be inappropriate for privacy.

**Comment by strugee** [comment] 2017-01-30 01:23
Closing as a duplicate of all those other issues.

**Closed by strugee** 2017-01-30 01:23 UTC
