### ISSUE TITLE
LibreOffice and Calligra Suite

### ISSUE THREAD

**Issue by maverick74** [nylira/prism-break#1416] opened 2015-09-30 18:48 UTC
Why isn't LibreOffice or Calligra Suite on the Productivity section?

**Comment by vyp** [comment] 2015-09-30 23:41
Online vs offline.

**Comment by alerque** [comment] 2015-10-01 05:27
This can be closed as a duplicate of #1342. It was also mentioned specifically in #834, #1384, #725, and #76.

**Closed** 2015-10-01 13:11 UTC
