### ISSUE TITLE
Recommended cheap vps or raspberry pi colocation

### ISSUE THREAD

**Issue by scastillobib** [nylira/prism-break#1052] opened 2014-07-04 13:24 UTC
Hi!

I'm thinking about self hosting my own mail server at home

The problem is that I have dynamic IP. Many SMTP servers will reject mail coming from a server with dynamic ip.

One solution could be host a SMTP server in a VPS or colocated raspberry pi.

Any recommendation?

Thank you

**Comment by yegortimoshenko** [comment] 2018-03-09 23:40
Not actionable, duplicate of #100.

**Closed by yegortimoshenko** 2018-03-09 23:40 UTC
